// atividade-frameworks/vue-app/src/components/PostList.vue
<template>
  <section class="blog-section">
    <div class="blog-inner">
      <div class="blog-content">
        <h2>Últimas do blog</h2>

        <div class="posts">
          <PostItem
            v-for="p in posts"
            :key="p.id"
            :title="p.title"
            :subtitle="p.subtitle"
          />
        </div>

        <a class="see-all" href="#">Ver tudo</a>
      </div>
    </div>
  </section>
</template>

<script setup>
import PostItem from "./PostItem.vue";

defineProps({
  posts: { type: Array, default: () => [] },
});
</script>

// atividade-frameworks/react-app/src/components/PostList.jsx
import PostItem from "./PostItem";

export default function PostList({ posts }) {
  return (
    <section className="blog-section">
      <div className="blog-inner">
        <div className="blog-content">
          <h2>Últimas do blog</h2>

          <div className="posts">
            {posts.map((p) => (
              <PostItem key={p.id} title={p.title} subtitle={p.subtitle} />
            ))}
          </div>

          <a className="see-all" href="#">
            Ver tudo
          </a>
        </div>
      </div>
    </section>
  );
}
