// atividade-frameworks/react-app/src/pages/About.jsx
export default function About() {
  return (
    <main className="page-section">
      <div className="page-inner">
        <h2>Sobre</h2>

        <p>
          Oi! Eu sou o Vitor, estudante de tecnologia e apaixonado por programação
          e segurança da informação. Gosto de aprender na prática, criando projetos
          e experimentando novas ferramentas.
        </p>

        <h3>Interesses</h3>
        <ul>
          <li>Desenvolvimento web (front-end e back-end)</li>
          <li>Segurança da informação (boas práticas, redes e fundamentos)</li>
          <li>Projetos pessoais para portfólio</li>
        </ul>

        <h3>Objetivos</h3>
        <p>
          Meu objetivo é evoluir como desenvolvedor, fortalecer minha base em
          segurança e construir um portfólio sólido. Também quero viajar o mundo
          e conhecer novas culturas enquanto aprendo cada vez mais.
        </p>
      </div>
    </main>
  );
}

// atividade-frameworks/vue-app/src/pages/About.vue
<template>
  <main class="page-section">
    <div class="page-inner">
      <h2>Sobre</h2>

      <p>
        Oi! Eu sou o Vitor, estudante de tecnologia e apaixonado por programação
        e segurança da informação. Gosto de aprender na prática, criando projetos
        e experimentando novas ferramentas.
      </p>

      <h3>Interesses</h3>
      <ul>
        <li>Desenvolvimento web (front-end e back-end)</li>
        <li>Segurança da informação (boas práticas, redes e fundamentos)</li>
        <li>Projetos pessoais para portfólio</li>
      </ul>

      <h3>Objetivos</h3>
      <p>
        Meu objetivo é evoluir como desenvolvedor, fortalecer minha base em
        segurança e construir um portfólio sólido. Também quero viajar o mundo e
        conhecer novas culturas enquanto aprendo cada vez mais.
      </p>
    </div>
  </main>
</template>
